import type { BrainConfig } from "./config.js";
import type { Entry } from "./entry.js";
import type { ChangeSet } from "./brain.js";
import { toolLabel } from "./tools.js";

export const BLOCK_BEGIN = "<!-- hamyad:begin (generated by `hamyad sync`; edit .brain/ instead) -->";
export const BLOCK_END = "<!-- hamyad:end -->";

function firstLine(body: string, n = 160): string {
  const line = body
    .split(/\r?\n/)
    .map((l) => l.replace(/^[#>*\-\s]+/, "").trim())
    .find((l) => l && !l.startsWith("**20") && !/^(asked|outcome|files changed|changes|commits)\b/i.test(l));
  if (!line) return "";
  return line.length > n ? line.slice(0, n - 1) + "…" : line;
}

const clip = (t: string, n: number) => {
  const one = (t || "").replace(/\s+/g, " ").trim();
  return one.length > n ? one.slice(0, n - 1) + "…" : one;
};
const day = (iso: string) => (iso || "").slice(0, 10);
const src = (e: Entry) => (e.source && e.source !== "file" ? ` · ${toolLabel(e.source)}` : "");

/**
 * Compact Markdown brief of the brain. This is what every agent reads first:
 * the CLAUDE.md / AGENTS.md block, `brain_context` over MCP, MEMORY.md and BRAIN.md.
 */
export function renderBrief(config: BrainConfig, entries: Entry[], opts: { maxChars?: number; heading?: boolean } = {}): string {
  const max = opts.maxChars ?? config.briefChars;
  const by = (k: string) => entries.filter((e) => e.kind === k);
  const decisions = by("decision").filter((e) => e.status !== "superseded" && e.status !== "reverted");
  const superseded = entries
    .filter((e) => (e.kind === "decision" || e.kind === "context") && e.status === "superseded")
    .sort((a, b) => (b.updated || "").localeCompare(a.updated || ""));
  const open = by("task").filter((e) => e.status !== "done" && e.status !== "dropped");
  const done = by("task").filter((e) => e.status === "done");
  const notes = by("note").filter((e) => e.status !== "superseded");
  const ctx = by("context").filter((e) => e.status !== "superseded");
  const sessions = by("session");
  const changes = by("change");
  const byId = new Map(entries.map((e) => [e.id, e]));

  const parts: string[] = [];
  if (opts.heading !== false) {
    parts.push(`# Project brain: ${config.project}`);
    parts.push(
      `_${decisions.length} active decisions · ${open.length} open tasks · ${notes.length} notes · ${sessions.length} sessions · ${changes.length} change sets. Shared by every AI tool on this project (Claude, Codex/ChatGPT, Gemini, Cursor, Copilot, Windsurf, aider…) via hamyad._`,
    );
  }
  const section = (title: string, items: Entry[], fmt: (e: Entry) => string, limit: number) => {
    if (!items.length) return;
    parts.push(`\n## ${title}`);
    for (const e of items.slice(0, limit)) parts.push(fmt(e));
    if (items.length > limit) parts.push(`- …and ${items.length - limit} more (use brain_list / \`hamyad list\`)`);
  };
  section("Context", ctx, (e) => `- **${e.title}**${firstLine(e.body) ? ` — ${firstLine(e.body, 240)}` : ""}`, 8);
  section("Decisions (in force)", decisions, (e) => `- ${day(e.created)} **${e.title}**${firstLine(e.body) ? ` — ${firstLine(e.body)}` : ""} \`${e.id}\`${src(e)}`, 12);
  section(
    "Superseded — do NOT follow these any more",
    superseded,
    (e) => {
      const by = e.supersededBy ? byId.get(e.supersededBy) : undefined;
      return `- ~~${e.title}~~ → ${by ? `**${by.title}** \`${by.id}\`` : e.supersededBy ? `\`${e.supersededBy}\`` : "(replaced)"} (${day(e.updated)})`;
    },
    6,
  );
  section(
    "Open tasks",
    open,
    (e) => `- [${e.status === "doing" ? "~" : e.status === "blocked" ? "!" : " "}] ${e.title} \`${e.id}\`${e.status !== "open" ? ` (${e.status})` : ""}`,
    15,
  );
  section("Recent notes", notes, (e) => `- ${day(e.updated)} **${e.title}**${firstLine(e.body) ? ` — ${firstLine(e.body, 120)}` : ""}${src(e)}`, 8);
  section("Recently done", done, (e) => `- [x] ${e.title}`, 5);
  section("Recent sessions (all tools)", sessions, (e) => `- ${day(e.updated || e.created)} [${toolLabel(e.source)}] ${e.title.replace(/^[^:]+:\s*/, "")}`, 8);
  section("Recent code changes", changes, (e) => `- ${day(e.updated || e.created)} [${toolLabel(e.source)}] ${e.title.replace(/^[^:]+:\s*/, "")}`, 5);
  if (!entries.length) parts.push("\n_The brain is empty. Record decisions, tasks and notes with the brain_remember tool or `hamyad add`._");

  let out = parts.join("\n").trim() + "\n";
  if (out.length > max) {
    const cut = out.lastIndexOf("\n", max - 40);
    out = out.slice(0, cut > 0 ? cut : max - 40) + "\n- …(brief truncated; use brain_search for more)\n";
  }
  return out;
}

/**
 * "What changed since your last session" — the block every tool gets first at
 * session start, so a code agent never works on a decision that chat replaced.
 */
export function renderChanges(cs: ChangeSet, opts: { since?: string; tool?: string; limit?: number } = {}): string {
  const lim = opts.limit ?? 12;
  const out: string[] = [];
  const who = (e: Entry) => toolLabel(e.source);
  if (cs.superseded.length || cs.added.length) {
    out.push(`⚠ DECISIONS CHANGED since your last ${opts.tool ? toolLabel(opts.tool) + " " : ""}session${opts.since ? ` (${opts.since.slice(0, 16).replace("T", " ")} UTC)` : ""}. Follow the new ones; do not act on the old ones:`);
    for (const { old, by } of cs.superseded.slice(0, lim)) {
      out.push(`- REPLACED: "${old.title}" \`${old.id}\` → ${by ? `"${by.title}" \`${by.id}\` (${who(by)})${firstLine(by.body) ? ` — ${clip(firstLine(by.body, 200), 200)}` : ""}` : "superseded"}`);
    }
    const replacing = new Set(cs.superseded.map((s) => s.by?.id).filter(Boolean));
    for (const e of cs.added.filter((e) => !replacing.has(e.id)).slice(0, lim)) {
      out.push(`- NEW ${e.kind}: "${e.title}" \`${e.id}\` (${who(e)})${firstLine(e.body) ? ` — ${clip(firstLine(e.body, 200), 200)}` : ""}`);
    }
  }
  if (cs.tasks.length) {
    out.push("Task updates:");
    for (const e of cs.tasks.slice(0, lim)) out.push(`- [${e.status}] ${e.title} \`${e.id}\` (${who(e)})`);
  }
  if (cs.sessions.length) {
    out.push("Other tools' sessions since then:");
    for (const e of cs.sessions.slice(0, 6)) out.push(`- [${who(e)}] ${clip(e.title.replace(/^[^:]+:\s*/, ""), 120)} \`${e.id}\``);
  }
  if (cs.notes.length) {
    out.push("New notes:");
    for (const e of cs.notes.slice(0, 6)) out.push(`- ${e.title} (${who(e)})`);
  }
  return out.join("\n");
}

const GUIDE = [
  "This project keeps ONE shared memory in `.brain/` that every AI tool reads and writes: Claude Code, Claude.ai chat, Codex, ChatGPT, Gemini CLI, Cursor, Copilot, Windsurf and aider.",
  "- Treat the decisions below as binding. Anything under **Superseded** is no longer true.",
  "- Record durable decisions, tasks and findings with the `brain_remember` MCP tool (or `hamyad add`). When a new decision replaces an old one, pass `supersedes: [old id]`.",
  "- Before re-deciding something, `brain_search` for an existing decision. Update task status with `brain_update`.",
];

/** The generated block placed in CLAUDE.md / AGENTS.md (and any other instruction file). */
export function renderInstructionBlock(config: BrainConfig, entries: Entry[]): string {
  const brief = renderBrief(config, entries, { heading: false, maxChars: config.briefChars });
  return [BLOCK_BEGIN, "## Shared project brain (hamyad)", ...GUIDE, "", brief.trim(), BLOCK_END].join("\n");
}

/** @deprecated 0.1 name */
export const renderClaudeBlock = renderInstructionBlock;

/** Insert or replace the generated block inside an existing instruction file. */
export function upsertBlock(text: string, block: string, heading = "# CLAUDE.md"): string {
  const start = text.indexOf("<!-- hamyad:begin");
  const end = text.indexOf(BLOCK_END);
  if (start !== -1 && end !== -1 && end > start) {
    return text.slice(0, start) + block + text.slice(end + BLOCK_END.length);
  }
  const sep = text.trim() ? (text.endsWith("\n") ? "\n" : "\n\n") : "";
  return (text.trim() ? text : `${heading}\n\n`) + sep + block + "\n";
}

// ------------------------------------------------------------------ MEMORY.md

export const MEMORY_HEAD = "<!-- hamyad:memory v1 — one-file project memory. The brief at the top is regenerated on every change; the entries below it are the data. Edit an entry block (or use hamyad / brain_* tools), not the brief. -->";
export const ENTRIES_MARK = "<!-- hamyad:entries -->";
export const fileOpen = (p: string) => `<!-- hamyad:file ${p} -->`;
export const FILE_CLOSE = "<!-- hamyad:/file -->";

/** Escape our own markers inside stored content so a block cannot end early. */
export const escapeMarkers = (s: string) => s.replace(/<!-- hamyad:/g, "<!-- hamyad\\:");
export const unescapeMarkers = (s: string) => s.replace(/<!-- hamyad\\:/g, "<!-- hamyad:");

/**
 * A single self-contained Markdown file: readable brief on top, every entry
 * below. Upload it to any chat tool that only takes files (ChatGPT/Claude
 * Projects, Gemini Gems, NotebookLM…), or use it *as* the store in a
 * Dropbox / Google Drive / iCloud folder (`hamyad init --store ~/Dropbox/x/MEMORY.md`).
 */
export function renderMemoryMd(config: BrainConfig, entries: Entry[], files: { path: string; content: string }[]): string {
  const brief = renderBrief(config, entries, { maxChars: 100_000 });
  const blocks = [...files]
    .filter((f) => f.path !== "MEMORY.md" && f.path !== "BRAIN.md")
    .sort((a, b) => a.path.localeCompare(b.path))
    .map((f) => `${fileOpen(f.path)}\n${escapeMarkers(f.content.replace(/\s+$/, ""))}\n${FILE_CLOSE}`);
  return [MEMORY_HEAD, brief.trim(), "", "---", "", "## All entries", "", ENTRIES_MARK, ...blocks, ""].join("\n");
}

/** Parse the entry blocks out of a MEMORY.md. Text outside blocks (the brief) is ignored. */
export function parseMemoryMd(text: string): { path: string; content: string }[] {
  const out: { path: string; content: string }[] = [];
  const re = /<!-- hamyad:file ([^\s]+) -->\r?\n([\s\S]*?)\r?\n?<!-- hamyad:\/file -->/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text))) out.push({ path: m[1], content: unescapeMarkers(m[2]) + "\n" });
  return out;
}
