import type { BrainConfig } from "./config.js";
import type { Entry } from "./entry.js";

export const BLOCK_BEGIN = "<!-- hamyad:begin (generated by `hamyad sync`; edit .brain/ instead) -->";
export const BLOCK_END = "<!-- hamyad:end -->";

function firstLine(body: string, n = 160): string {
  const line = body
    .split(/\r?\n/)
    .map((l) => l.replace(/^[#>*\-\s]+/, "").trim())
    .find((l) => l && !l.startsWith("**20"));
  if (!line) return "";
  return line.length > n ? line.slice(0, n - 1) + "…" : line;
}

const day = (iso: string) => (iso || "").slice(0, 10);
const src = (e: Entry) => (e.source && e.source !== "file" ? ` · ${e.source}` : "");

/**
 * Compact Markdown brief of the brain. This is what Claude reads first, in every
 * surface: the CLAUDE.md block, `brain_context` over MCP and `.brain/BRAIN.md`.
 */
export function renderBrief(config: BrainConfig, entries: Entry[], opts: { maxChars?: number; heading?: boolean } = {}): string {
  const max = opts.maxChars ?? config.briefChars;
  const by = (k: string) => entries.filter((e) => e.kind === k);
  const decisions = by("decision").filter((e) => e.status !== "superseded" && e.status !== "reverted");
  const open = by("task").filter((e) => e.status !== "done" && e.status !== "dropped");
  const done = by("task").filter((e) => e.status === "done");
  const notes = by("note");
  const ctx = by("context");
  const sessions = by("session");

  const parts: string[] = [];
  if (opts.heading !== false) {
    parts.push(`# Project brain: ${config.project}`);
    parts.push(
      `_${decisions.length} active decisions · ${open.length} open tasks · ${notes.length} notes · ${sessions.length} sessions. Shared by Claude Code, Claude.ai chat, Claude Desktop and GitHub via hamyad._`,
    );
  }
  const section = (title: string, items: Entry[], fmt: (e: Entry) => string, limit: number) => {
    if (!items.length) return;
    parts.push(`\n## ${title}`);
    for (const e of items.slice(0, limit)) parts.push(fmt(e));
    if (items.length > limit) parts.push(`- …and ${items.length - limit} more (use brain_list / \`hamyad list\`)`);
  };
  section("Context", ctx, (e) => `- **${e.title}**${firstLine(e.body) ? ` — ${firstLine(e.body, 240)}` : ""}`, 8);
  section("Decisions", decisions, (e) => `- ${day(e.created)} **${e.title}**${firstLine(e.body) ? ` — ${firstLine(e.body)}` : ""} \`${e.id}\`${src(e)}`, 12);
  section(
    "Open tasks",
    open,
    (e) => `- [${e.status === "doing" ? "~" : e.status === "blocked" ? "!" : " "}] ${e.title} \`${e.id}\`${e.status !== "open" ? ` (${e.status})` : ""}`,
    15,
  );
  section("Recent notes", notes, (e) => `- ${day(e.updated)} **${e.title}**${firstLine(e.body) ? ` — ${firstLine(e.body, 120)}` : ""}${src(e)}`, 8);
  section("Recently done", done, (e) => `- [x] ${e.title}`, 5);
  section("Recent sessions", sessions, (e) => `- ${day(e.created)} ${e.title}${src(e)}`, 5);
  if (!entries.length) parts.push("\n_The brain is empty. Record decisions, tasks and notes with the brain_remember tool or `hamyad add`._");

  let out = parts.join("\n").trim() + "\n";
  if (out.length > max) {
    const cut = out.lastIndexOf("\n", max - 40);
    out = out.slice(0, cut > 0 ? cut : max - 40) + "\n- …(brief truncated; use brain_search for more)\n";
  }
  return out;
}

export function renderClaudeBlock(config: BrainConfig, entries: Entry[]): string {
  const brief = renderBrief(config, entries, { heading: false, maxChars: config.briefChars });
  return [
    BLOCK_BEGIN,
    "## Shared project brain (hamyad)",
    "This project keeps one shared memory in `.brain/` (git-tracked) that Claude.ai chat, Claude Desktop and Claude Code all read and write.",
    "- Record durable decisions, tasks and findings with the `brain_remember` MCP tool (or `hamyad add`), not only in your own auto memory.",
    "- Before re-deciding something, `brain_search` for an existing decision. Update task status with `brain_update`.",
    "",
    brief.trim(),
    BLOCK_END,
  ].join("\n");
}

/** Insert or replace the generated block inside an existing CLAUDE.md text. */
export function upsertBlock(text: string, block: string): string {
  const start = text.indexOf("<!-- hamyad:begin");
  const end = text.indexOf(BLOCK_END);
  if (start !== -1 && end !== -1 && end > start) {
    return text.slice(0, start) + block + text.slice(end + BLOCK_END.length);
  }
  const sep = text.trim() ? (text.endsWith("\n") ? "\n" : "\n\n") : "";
  return (text.trim() ? text : "# CLAUDE.md\n\n") + sep + block + "\n";
}
