import { existsSync, promises as fs, readFileSync } from "node:fs";
import path from "node:path";
import { Brain } from "../core/brain.js";
import { FsBackend } from "../backends/fs.js";
import { renderBrief, renderClaudeBlock, upsertBlock } from "../core/render.js";
import { gitRoot } from "./git.js";

export const BRAIN_DIR = ".brain";

export interface Project {
  root: string;
  brainDir: string;
  brain: Brain;
  isGit: boolean;
}

/** Find the project root: nearest ancestor with `.brain/`, else the git root, else cwd. */
export function findRoot(start: string): string {
  let dir = path.resolve(start);
  for (;;) {
    if (existsSync(path.join(dir, BRAIN_DIR))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return gitRoot(start) || path.resolve(start);
}

export function openProject(dir: string | undefined, source?: string): Project {
  const root = findRoot(dir || process.cwd());
  const brainDir = path.join(root, BRAIN_DIR);
  return { root, brainDir, brain: new Brain(new FsBackend(brainDir), { source }), isGit: !!gitRoot(root) };
}

async function writeIfChanged(file: string, content: string): Promise<boolean> {
  const old = existsSync(file) ? readFileSync(file, "utf8") : undefined;
  if (old === content) return false;
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, content, "utf8");
  return true;
}

/** Regenerate `.brain/BRAIN.md` (for Claude.ai GitHub project knowledge) and the CLAUDE.md block. */
export async function regenerate(p: Project): Promise<{ brainMd: boolean; claudeMd: boolean }> {
  const { config, entries } = await p.brain.snapshot();
  const brief = renderBrief(config, entries, { maxChars: 100_000 });
  const brainMd = await writeIfChanged(
    path.join(p.brainDir, "BRAIN.md"),
    `<!-- Generated by hamyad. Add this folder (or just this file) to a Claude.ai Project via the GitHub integration. -->\n${brief}`,
  );
  let claudeMd = false;
  if (config.claudeMd) {
    const file = path.join(p.root, "CLAUDE.md");
    const old = existsSync(file) ? readFileSync(file, "utf8") : "";
    claudeMd = await writeIfChanged(file, upsertBlock(old, renderClaudeBlock(config, entries)));
  }
  return { brainMd, claudeMd };
}

// ------------------------------------------------------------------ local state

export interface LocalState {
  lastSessionStart?: string;
  sessionStarts?: Record<string, string>;
}

export function readState(p: Project): LocalState {
  try {
    return JSON.parse(readFileSync(path.join(p.brainDir, ".state.json"), "utf8"));
  } catch {
    return {};
  }
}

export async function writeState(p: Project, s: LocalState) {
  if (s.sessionStarts) {
    const keys = Object.keys(s.sessionStarts);
    for (const k of keys.slice(0, Math.max(0, keys.length - 20))) delete s.sessionStarts[k];
  }
  await fs.mkdir(p.brainDir, { recursive: true });
  await fs.writeFile(path.join(p.brainDir, ".state.json"), JSON.stringify(s, null, 2) + "\n");
}
